My Project: src/main.hpp File Reference
main.hpp File Reference
Functions
int main (int argc, char **argv)
void testNumbers (void)
void testDog (void)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 6 of file main.cpp.
{
     printf("Start\n\n");
     testNumbers();
     printf("\n");
     testDog();
     printf("\nEnd\n");
     return 0;
 }
References testDog(), and testNumbers().
testDog()
void testDog (void)
Definition at line 27 of file main.cpp.
                    {
     printf("Testing Dog...\n");
     Dog* fido = new Dog("Fido");
     for (int i = 0; i < 5; i++) {
         fido->bark();
     }
     fido->sleep(1);
     for (int i = 0; i < 5; i++) {
         fido->bark();
     }
     fido->sleep(1000);
     fido->run(6);
     fido->run(3);
     fido->sleep(1);
     fido->bark();
     printf("Dog test complete.\n");
 }
References Dog::bark(), Dog::run(), and Dog::sleep().
Referenced by main().
testNumbers()
void testNumbers (void)
Definition at line 15 of file main.cpp.
{
     int x = 5;
     int y = 6;
     printf("Testing numbers...\n");
     printf("%d squared is %d\n", x, square(x));
     printf("%d times %d is %d\n", x, y, multiply(x, y));
     printf("The magic number is %d\n", MAGIC_NUMBER);
     printf("%d magicked is %d\n", x, magic(x));
     printf("Fight: %d\n", battleOfTheFiveGods());
     printf("Number test complete.\n");
 }
References battleOfTheFiveGods(), magic(), MAGIC_NUMBER, multiply(), and square().
Referenced by main().